### ISSUE TITLE
None of my sensors are available with v2.0.0-beta6

### ISSUE THREAD

**Issue by csharpWorm** [custom-components/grocy#100]
Seeing the following messages in my logs. All of my groovy sensors and binary sensors say unavailable after upgrading repository to v2.0.0-beta6
![D75CCFF7-7B74-445E-8AE8-019E665D9BC0](https://user-images.githubusercontent.com/55300427/93551115-0f1a7400-f93b-11ea-8bd9-724ee329dec2.jpeg)

**Comment by csharpWorm** [comment]
This may or may not have anything to do with the sensors being unavailable

**Comment by isabellaalstrom** [comment]
Can you please check to see if you have disabled sensors.

**Comment by csharpWorm** [comment]
All of the sensors are enabled. Do I need to remove the grout I refractions and re add with a new api key?

**Comment by isabellaalstrom** [comment]
I think that may have been auto correct 😄 But yes, try with removing and re-adding the integration and see if that makes any difference.

**Comment by csharpWorm** [comment]
All of the sensors are enabled.

**Comment by csharpWorm** [comment]
As a matter of fact I get the same behavior with all of the beta versions

**Comment by isabellaalstrom** [comment]
Please enable debugging for the integration in the log and see if you get anything else. The error shown in the first post should not make the sensors unavailable.
What are your versions of Grocy, the integration and HA?
What version did you upgrade the integration from?

**Comment by csharpWorm** [comment]
Thanks for the advanced debugging clue. The sensors weren’t being registered properly and being disabled by integration. After cleaning up the sensors in core.entity_registry by setting the disabled tag to null they started working.
