### ISSUE TITLE
URL for grocy API

### ISSUE THREAD

**Issue by spriggsy** [custom-components/grocy#101]
Im having issues getting past the first hurdle.
The Addon is installed, when adding the integration it loads a form asking for the URL address, API Key and port

My grocy is installed via the official addon and works fine from within Homeassistant and also from a web page

I have tried setting the URL as 
    127.0.0.1
    192.168.1.145 ( this is the internal address of the pi)
    xxxxxxxx.ddns.net ( this is my noip address with correct port forwarding)
    http://xxxxxxxx.ddns.com

both return an Unknown error in the form

I believe this may have something to do with the extra  .'s in the address as if I set the address to http://xxxxxxxx.ddns it tries to connect, but obviously fails

How can I access the local running grocy install?
many thanks
Spriggsy

**Comment by isabellaalstrom** [comment]
Have you done the Add-on port configuration as per the image in the read me?

**Comment by spriggsy** [comment]
Hi, yes the port has been set to 9192. Just restarting again to double check.

**Comment by isabellaalstrom** [comment]
The internal address of the pi should then work. But you have to have http or https (according to your install, also, do you have that?

**Comment by spriggsy** [comment]
yes Ive tried all variations of the address. I can access the grocy web page fine if I type 192.168.1.145:9192 directly into the address bar of chrome.

It must not be installed correctly? Ill try uninstalling ad trying again.

thank you

**Comment by isabellaalstrom** [comment]
What versions do you have? Of ha, grocy and this integration?

**Comment by spriggsy** [comment]
grocy 2.7.1
ha 0.115
your intergration 1.0.2

**Comment by isabellaalstrom** [comment]
Please try the latest beta of the integration instead!

**Comment by spriggsy** [comment]
thank you, Ill give it a go now

**Comment by spriggsy** [comment]
Thank you for your help, your latest beta version6 has installed and accepted http://192.168.1.145

Sofar so good

thanks again
spriggsy
