### ISSUE TITLE
'yearly' is not recognized as a valid PeriodType but is available in grocy

### ISSUE THREAD

**Issue by strikeir13** [custom-components/grocy#113]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
In grocy, selecting "yearly" as a Period Type for a chore results in an error in the Home Assistant log. While the error in the log is not a significant issue, the Lovelace Grocy Chores Card causes the entire lovelace view to not display any cards and I suspect the root cause is this error.
![image](https://user-images.githubusercontent.com/688283/103044125-f8407a80-4544-11eb-8459-88ae7747574f.png)

**Expected behavior**
Selecting "yearly" does not make the chores card disappear.

**To Reproduce**
1. Install grocy
2. Create chore with Period Type of "yearly"
3. Install grocy custom component
4. Install lovelace grocy Chores card.
5. Lovelace view with Chores card does not display any cards.

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant 2020.12.1
grocy addon, version 0.9.2
grocy custom component 2.0.2

**How do you have Grocy installed? Add-on or external?**
Add-on

**Have you added debugging to the log, and what does the log say?**
No debugging added besides default. Log errors shown in screenshot above

**JSON service data (if related to using a service)**
```json
{

}
```

**Additional context**

**Comment by isabellaalstrom** [comment]
Should be fixed in latest release.
