### ISSUE TITLE
Request Battery Tracking

### ISSUE THREAD

**Issue by GlennGoddard** [custom-components/grocy#116]
Battery Support has been added to pygrocy
[148](https://github.com/SebRut/pygrocy/pull/148)

Request Battery Tracking be added for custom component.

**Comment by isabellaalstrom** [comment]
@GlennGoddard What kind of information would you like to have in hass? I don't use the battery tracking myself.

**Comment by GlennGoddard** [comment]
The same info as the chores integration.  I use it just like chores but for batteries.
Unfortunately, I am not at home right now so I can't pull the exact info from Grocy.
I will post the relevant info when I get home; but I'm fairly sure the info that matters is Name and date just like chores.

(for the card) I don't know if it would be better to have its own card or pull it into the chores card.

**Comment by GlennGoddard** [comment]
Battery section has
Battery
Used In
Last Charged
Next planned charge cycle (ie when due)

Sorry for the delay, very busy week.

**Comment by isabellaalstrom** [comment]
No problem, I've not had time to look at it anyways. Right now I'm trying to make the tasks card integrated in the chores card instead, and after that I can probably look at this.
