### ISSUE TITLE
"done_by" parameter not working as expected for the execute_chore service for multiple users

### ISSUE THREAD

**Issue by Avdbergnmf** [custom-components/grocy#119]
**Describe the bug**
When calling the following:  
```yaml
service: grocy.execute_chore
data:
  chore_id: 0
  done_by: 2
```  

I get the following error:  
`Failed to call service grocy/execute_chore. 500 Server Error: Internal Server Error for url: https://192.168.178.52:9192/api/chores/0/execute`  

Even though there's multiple users, I seem to only be able to access the admin used, as when using id 0 or 1, the service call works just fine.

I'd like to have tasks completed by different users by calling the service using NFC tags.

**Expected behavior**
I expect that the chore execution gets registered and is completed by the used with id 2 (or any other user that is not the default: id=0 or 1)

**To Reproduce**
1. Go to developer tools, services, look for grocy.execute_chore
2. For the service data fill in `done_by: 2` (and make sure there are 2, or more, users in your grocy app)
3. Call Service

**What is your installed versions of Home Assistant, Grocy and this integration?**
Grocy:  0.11.1  
Grocy Custom Component: v3.0.1  
Home Assistant Core 2021.3.2

**How do you have Grocy installed? Add-on or external?**
Add-on
**Have you added debugging to the log, and what does the log say?**
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/grocy/services.py:191
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:54:04 (2 occurrences)
Last logged: 21:54:31

[2820324224] 500 Server Error: Internal Server Error for url: https://192.168.178.52:9192/api/chores/0/execute
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/grocy/services.py", line 99, in async_call_grocy_service
    await async_execute_chore_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 191, in async_execute_chore_service
    coordinator.api.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 98, in execute_chore
    return self._api_client.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 617, in execute_chore
    return self._do_post_request(f"chores/{chore_id}/execute", data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 560, in _do_post_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://192.168.178.52:9192/api/chores/0/execute
```

Simultaneously the following error pops up, which may or may not be related:
```
Logger: homeassistant.util.async_
Source: util/async_.py:129
First occurred: 21:54:03 (2 occurrences)
Last logged: 21:54:31

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for grocy doing I/O at custom_components/grocy/services.py, line 191: coordinator.api.execute_chore(chore_id, done_by, tracked_time)
```

**JSON service data (if related to using a service)**
not sure... Is the yaml data sufficient, I don't know where to get the json service data from.

**Comment by MagicMountainMan** [comment]
I think the issue has more to do with Grocy V3. When I go into the Chore Tracking tab of Grocy, I cannot track a chore manually by selecting any user besides myself. I have to log into that user and then track the chore. This was not the case in V2 which is why I'm assuming it's broken.

**Comment by MagicMountainMan** [comment]
In the official Grocy GitHub repo I found this issue: [https://github.com/grocy/grocy/issues/1260](url) that I believe addresses the problem. I think the fix has to wait until they release the next version of Grocy unfortunately. This exact issue has been frustrating me for a few weeks now as I have roommates and we all use Grocy chore reminders...

**Comment by Avdbergnmf** [comment]
Thanks for the reply! I think you're right... I did manage to find a way to get something to work (though I have no idea how I could implement this into this software).
You CAN execute chores as different users, but you need to generate a different API key for each user. For example, the API key of user 2 can only execute chores as user 2. Also: user id 0 refers to the user that owns the API key, not the default / admin user. So using id 0 will always refer to the user that owns the API key that is used.

how i tested this:

- If you go to the REST API (inside Grocy, wrench icon & click REST API), 
- Authenticate the api with the API key (top-right click authenticate) of the user you want to execute the task with
- scroll down to chores, click the POST: /chores/{choreId}/execute --> click Try it out
  - Fill in your chore id, and change the request body to:
    ```
    {
      "done_by": 0
    }
    ```
  - Hit execute 

assigning any user other than default, or the user that owns the API key returns:
```
{
  "error_message": "Undefined class constant 'PERMISSION_CHORE_TRACK_EXECUTION_EXECUTION'",
  "error_details": {
    "stack_trace": "#0 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\\Controllers\\ChoresApiController->TrackChoreExecution()\n#1 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#2 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()\n#3 /var/www/grocy/middleware/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n#4 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): Grocy\\Middleware\\JsonMiddleware->__invoke()\n#5 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()\n#6 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\\MiddlewareDispatcher->handle()\n#7 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\\Routing\\Route->run()\n#8 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\\Routing\\RouteRunner->handle()\n#9 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\LocaleMiddleware->__invoke()\n#10 /var/www/grocy/middleware/AuthMiddleware.php(76): class@anonymous->handle()\n#11 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#12 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()\n#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()\n#14 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()\n#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()\n#16 /var/www/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle()\n#17 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#18 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()\n#19 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\\MiddlewareDispatcher->handle()\n#20 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\\App->handle()\n#21 /var/www/grocy/app.php(94): Slim\\App->run()\n#22 /var/www/grocy/public/index.php(45): require_once('/var/www/grocy/...')\n#23 {main}",
    "file": "/var/www/grocy/controllers/ChoresApiController.php",
    "line": 84
  }
}
```

So I suppose if you make your own automation and define multiple grocy api keys in your secrets.yaml you might be able to execute as different users. 

off-topic:
Could you share with me how you currently set up your chores system? I'm trying to set up something similar myself but I find I'm struggling as I'm quite new to HA

**Comment by Avdbergnmf** [comment]
The issue you link to (Bug: "Done by" in chore tracking can only be user which is currently logged in #1260) indeed seems to address the issue.

As per https://github.com/grocy/grocy/issues/1295 it seems it'll be fixed with the next update. I suppose the solution suggested by berrnd (If you want to have this now, replace the file controllers/ChoresApiController.php with [that one](https://raw.githubusercontent.com/grocy/grocy/27169e1428ca307401a197fa679d6de6b8e7c607/controllers/ChoresApiController.php)) requires you to build your own version of the application? Or is there some file inside of my HA install that I can edit...

Thanks again for you help.

**Comment by MagicMountainMan** [comment]
I use the Lovelace Grocy chores card that can be found in HACS which is what I have used to expose chores to my Lovelace dash. The card allows you to assign a user to it, and I use a state-switch to show the version of the card for that user when they log in to Home Assistant. 

And I did go looking to replace the file but I couldn't find where the add-ons are stored as I don't think they are exposed by default in the addon folder in the root of my Home Assistant VM. To be honest I didn't go looking that hard though because I kind of gave up and I'm just waiting for the fix to roll out.

**Comment by isabellaalstrom** [comment]
If you are running the addon it will be difficult to make changes to the Grocy files. You'll unfortunately have to wait for a fix in Grocy. I will close this issue since it's not an issue with the integration.

**Comment by isabellaalstrom** [comment]
This is the issue in Grocy github (I was having trouble with the link posted above) if you want to keep track. https://github.com/grocy/grocy/issues/1260

**Comment by Avdbergnmf** [comment]
> This is the issue in Grocy github (I was having trouble with the link posted above) if you want to keep track. [grocy/grocy#1260](https://github.com/grocy/grocy/issues/1260)

Yes, thank you for your reply & your work :)
