### ISSUE TITLE
Can't find grocy in integration

### ISSUE THREAD

**Issue by pjrt** [custom-components/grocy#120]
I'm following the README but when it says `In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Grocy"`, I can't find that integration. 

![image](https://user-images.githubusercontent.com/1610164/111084412-a0346700-84e8-11eb-9d8a-d4ce2679aeb0.png)

![image](https://user-images.githubusercontent.com/1610164/111084421-aaeefc00-84e8-11eb-86ea-6ebd82b1dc8f.png)

I'm using version v3.0.1.

**Comment by pjrt** [comment]
Can't really find anything in the logs either.

**Comment by jofotoo** [comment]
You install it into HACS first, then it can show up in the regular integrations list, but there may be an issue with the grocy integration as it's caused a few people's HA UI's to not load. Might want to hold off for now.

**Comment by pjrt** [comment]
I did install it via HACS (that's what the first image is trying to show).

**Comment by jofotoo** [comment]
ah, sorry.  Refreshed your browser and deleted cache? Sometimes you have to do that for certain changes to take effect, but it's also possible it's temporarily unavailable.

**Comment by pjrt** [comment]
Ah, you are correct. Clearing my browser cache did it. Thanks!
