### ISSUE TITLE
db-changed-time

### ISSUE THREAD

**Issue by adtwomey** [custom-components/grocy#123]
Expected behavior
Being able to get date from Grocy.

To Reproduce
no date is getting upload from grocy
What is your installed versions of Home Assistant, Grocy and this integration?
Home Assistant core-2021.3.2
Grocy v3.0.1
Grocy integration v3.0.1

How do you have Grocy installed? Add-on or external?
- unraid addon -
Have you added debugging to the log, and what does the log say?
no

``2021-04-11 16:06:20 ERROR (MainThread) [custom_components.grocy] Update of Expired_products failed with 404 Client Error: Not Found for url: http://###.###.#.##:9283/:9283/api/system/db-changed-time``

**Comment by SebRut** [comment]
Looks like you set up the grocy integration with a trailing slash and port for the grocy url. Could you try re-adding the integration without the slash and port at the end please?

**Comment by isabellaalstrom** [comment]
I will close this, try @SebRut suggestion, and if that doesn't work we can open again.

**Comment by adtwomey** [comment]
Thanks yes that work sorry
