### ISSUE TITLE
Update of Tasks failed with Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by denko81** [custom-components/grocy#138]
I'm getting this error. 

This error originated from a custom integration.

Logger: custom_components.grocy
Source: custom_components/grocy/__init__.py:104
Integration: Grocy (documentation)
First occurred: 17:47:16 (278 occurrences)
Last logged: 20:05:53

Update of Expired_products failed with Expecting value: line 1 column 1 (char 0)
Update of Tasks failed with Expecting value: line 1 column 1 (char 0)

**Comment by isabellaalstrom** [comment]
Please create a new issue with the template filled out.
https://github.com/custom-components/grocy/issues/new?assignees=&labels=&template=bug_report.md&title=
