### ISSUE TITLE
Tasks and Chores should show 0, not unknown, when no items

### ISSUE THREAD

**Issue by isabellaalstrom** [custom-components/grocy#140]

**Comment by isabellaalstrom** [comment]
@SebRut Do you know if this is something on the integration end or if it's pygrocy that returns unknown when it should return for example 0 tasks? The entity should not be unknown just because you don't have any tasks, right?

**Comment by SebRut** [comment]
I just tried `len(grocy.tasks())` with no existing tasks (or the tasks feature enabled) and got `0` as an response. So I guess this problem is located on the integration side.
