### ISSUE TITLE
Meal plan does not support notes

### ISSUE THREAD

**Issue by bregol** [custom-components/grocy#147]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
When I add a Note or a Product to the meal plan, I get this error:
[custom_components.grocy] Update of Meal_plan failed with 'NoneType' object has no attribute 'name'

Everything works fine if I remove Notes and Products from the meal plan so that it only has Recipes.

**Expected behavior**
Notes and Products would be handled as well, so that my meal plan widget would display a meal plan that isn't a recipe (ie. a note saying "out to eat"

**To Reproduce**
1. Pull up the meal plan in Grocy
2. On today, drop down the arrow next to the plus button and choose to add either a Note or a Product
3. Add it to your Grocy meal plan
4. Check your Home Assistant logs

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy?**
I only have the meal plan sensor enabled, as I am just starting to test and set up this integration. It works if I only add Recipes to the meal plan.

**What is your installed versions of Home Assistant, Grocy and this integration?**
Grocy: 3.0.1
HA: core-2021.7.2
This integration: 3.0.5

**How do you have Grocy installed? Add-on or external?**
Separate docker container

**Have you added debugging to the log, and what does the log say?**
[custom_components.grocy] Update of Meal_plan failed with 'NoneType' object has no attribute 'name'

**Comment by isabellaalstrom** [comment]
@bregol Please download latest beta and see if that fixed this.
