### ISSUE TITLE
Add support for new meal plan "sections" in grocy v 3.1.0

### ISSUE THREAD

**Issue by ElPiloto** [custom-components/grocy#149]
**Describe the bug**
As of [grocy v3.1.0](https://grocy.info/changelog), meal plans have "sections."  This allows breaking up the meal plan into breakfast, lunch, snack, dinner, etc.  However, the grocy integration does not currently expose the "section" associated with a meal plan entry.

**Expected behavior**
`sensor.grocy_meal_plan['meals]` should populate "section".

**To Reproduce**
1. In grocy, add a meal to your meal plan and enter a meal plan section for the meal.
2. In home assistant, go to developer tools --> "states" and select "sensor.grocy_meal_plan"
3. Observe that "section" is missing from `sensor.grocy_meal_plan["meals"]`

### General information to help debugging:
**I can see all information about `sensor.grocy_meal_plan` but information about the `section` is missing for my meals.**

**What is your installed versions of Home Assistant, Grocy and this integration?**
- grocy v3.1.0
- home assistant: core-2021.6.6
- grocy integration: v 3.0.5

**How do you have Grocy installed? Add-on or external?**
I have grocy installed as an add-on.

**Have you added debugging to the log, and what does the log say?**
Not applicable, pretty sure "section" is missing because it's a brand new feature and needs to be implemented.

**JSON service data (if related to using a service)**
n/a

**Comment by ElPiloto** [comment]
Also filed a corresponding bug over at pygrocy as the data model for meal plans needs to be updated: https://github.com/SebRut/pygrocy/issues/172

**Comment by Deejayfool** [comment]
I'm also interested in getting the section of each meal :) . Can I know if it's something you will work on ?
Or maybe there is a workaround to get this info ?
