### ISSUE TITLE
Barcodes not supported for inventory management

### ISSUE THREAD

**Issue by Didgeridrew** [custom-components/grocy#154]
**Describe the bug**
After updating to v3.2.0 yesterday none of my sensors are working.  Prior to the update, they were working.
Currently binary_sensor.grocy_overdue_chores and binary_sensor.grocy_overdue_tasks are reporting "off" when they should be reporting "on".  Also sensor.grocy_chores and sensor.grocy_tasks are both reporting "unknown" when they should be reporting "3" and "2" respectively.

**Expected behavior**
Sensors should not have a value of "unknown" 

**To Reproduce**
1. Go to 'Developer Tools>States'
2. Input 'sensor.grocy_chores'
3. See error

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy?**

I have all sensor enable except binary_sensor.grocy_expired_products, they were all working fine prior to update.  Currently all binary sensors return "off" and all sensors return "unknown".

**What is your installed versions of Home Assistant, Grocy and this integration?**

 Grocy Add-on version: 0.15.0
 Grocy Custom Component version: 3.2.0
 System: Home Assistant OS 6.2
 Home Assistant Core: 2021.8.8
 Home Assistant Supervisor: 2021.06.8

**How do you have Grocy installed? Add-on or external?**

Add-on

**Have you added debugging to the log, and what does the log say?**

> Logger: homeassistant.components.binary_sensor
> Source: custom_components/grocy/json_encode.py:26
> Integration: Binary sensor (documentation, issues)
> First occurred: 12:05:37 PM (1 occurrences)
> Last logged: 12:05:37 PM
> 
> grocy: Error on device update!
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
> await entity.async_device_update(warning=False)
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
> await task
> File "/config/custom_components/grocy/entity.py", line 57, in async_update
> await self.coordinator.async_request_refresh()
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 141, in async_request_refresh
> await self._debounced_refresh.async_call()
> File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
> await task
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
> await self._async_refresh(log_failures=True)
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
> update_callback()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in _async_write_ha_state
> extra_state_attributes = self.device_state_attributes
> File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
> return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
> File "/usr/local/lib/python3.9/json/init.py", line 234, in dumps
> return cls(
> File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
> chunks = self.iterencode(o, _one_shot=True)
> File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
> return _iterencode(o, 0)
> File "/config/custom_components/grocy/json_encode.py", line 26, in default
> return json.JSONEncoder.default(self, o)
> File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
> raise TypeError(f'Object of type {o.class.name} '
> TypeError: Object of type ProductBarcodeData is not JSON serializable

**Comment by mshuflin** [comment]
I have the same issue

Logger: homeassistant.components.binary_sensor
Source: custom_components/grocy/json_encode.py:26
Integration: Binary sensor (documentation, issues)
First occurred: 3:25:42 PM (1 occurrences)
Last logged: 3:25:42 PM

grocy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/config/custom_components/grocy/entity.py", line 57, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 141, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable

**Comment by isabellaalstrom** [comment]
This is an issue when barcodes are added I think. However I would say the issue originates in pygrocy: https://github.com/SebRut/pygrocy/issues

**Comment by Didgeridrew** [comment]
> This is an issue when barcodes are added I think. Do you use barcodes?

Isabella, thank you for pointing me in the right direction.

I do use barcodes for inventory, but I did not have this error prior to the update.

Since I mostly use the custom component so I can use the task and chore lovelace card, I have disabled all the sensor entities that are related to inventory management.  Now the chore and task related sensors are showing up fine.

**Comment by renarena** [comment]
What does inventory mean? products?
I have the same error, but imho using barcode scanning for product handling is a main feature of grocy. 
Does this mean i have to remove all barcodes to use this?

**Comment by rickgardner077** [comment]
I can confirm, have the same error (see below for log). Error resolved after deleting barcode info from items. Barcodes in Grocy seem to break the Home Assistant integration.
`

Logger: homeassistant
Source: custom_components/grocy/json_encode.py:26
Integration: Grocy (documentation, issues)
First occurred: 08:38:27 (14 occurrences)
Last logged: 08:46:05
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _async_write_ha_state
    self.device_state_attributes is not None
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable

`

**Comment by isabellaalstrom** [comment]
This is unfortunately correct, barcodes are not supported as of yet in the integration. This is probably an easy fix if anyone wants to help out, I don't have the time right now.

**Comment by isabellaalstrom** [comment]
@Didgeridrew and everyone else having this problem - Please download latest beta version to see if this is fixed.

**Comment by rickgardner077** [comment]
I installed beta 4.1.4b, added a new product with barcode, HA log no longer shows an error pertaining to this problem.

However, there are several breaking errors pertaining to invalid datetime format which break my Shopping List and Chores integration. Should I open an issue for this?

**Comment by isabellaalstrom** [comment]
@rickgardner077 Yes please.
