### ISSUE TITLE
Can't consume decimal amounts

### ISSUE THREAD

**Issue by yordanov-alexandar** [custom-components/grocy#157]
I am trying to consume amount less than 1:
service: grocy.consume_product_from_stock
data:
  transaction_type: CONSUME
  product_id: '4'
  amount: 0.1

I get this error:
Error handling message: expected int for dictionary value @ data['amount']. Got None

In the grocy android app I can consume decimal amounts so it should be possible to do and I think this is a valid usecase

**Comment by isabellaalstrom** [comment]
@yordanov-alexandar  Please download latest beta version to see if this is fixed.

**Comment by yordanov-alexandar** [comment]
Thank you
I have updated from 4.0.1 to 4.1.4b.
Consuming now works with decimal amounts - the change is reflected on the grocy server.
However my sensors stopped working - this is the error i see in the Home Assistant log:

Logger: custom_components.grocy
Source: custom_components/grocy/__init__.py:104
Integration: Grocy (documentation, issues)
First occurred: 11:01:15 (178 occurrences)
Last logged: 11:44:56

    Update of Shopping_list failed with 1 validation error for ProductDetailsResponse last_used invalid datetime format (type=value_error.datetime)
    Update of Stock failed with 1 validation error for CurrentStockResponse product -> product_group_id value is not a valid integer (type=type_error.integer)

**Comment by isabellaalstrom** [comment]
@yordanov-alexandar Please create a new issue for that :)

**Comment by ludeeus** [comment]
No need, see <https://github.com/SebRut/pygrocy/issues/215>
