### ISSUE TITLE
external installation without port

### ISSUE THREAD

**Issue by jon-daemon** [custom-components/grocy#158]
It seems that [this](https://github.com/SebRut/pygrocy/issues/121) issue has been closed. How could we test it with the custom component?

**Comment by isabellaalstrom** [comment]
I think it requires changes in the config flow before it's testable.

**Comment by ludeeus** [comment]
A port is always used, if you think you are not using a port you are using one of the defaults.
443 for SSL and 80 for non SSL.
In the config flow use 443 or 80 if you access grocy "without" a port.
