### ISSUE TITLE
All entities unavailable

### ISSUE THREAD

**Issue by blakenorthrup** [custom-components/grocy#159]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
I have Grocy installed on Unraid, and added the HACS add-on in HA, then enabled all entities, but they all show as Unavailable.

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy? All entities are enabled, none are available.

**What is your installed versions of Home Assistant, Grocy and this integration? HA version 2021.10.4, Grocy 3.1.2 on Unraid, Grocy HACS 3.2.0

**How do you have Grocy installed? Add-on or external? Grocy external on Unraid, with HACS add-on

**Have you added debugging to the log, and what does the log say? LOG- 2021-10-13 17:06:02 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration grocy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

Grocy install on Unraid works like a charm, along with the phone app, but the HACS install shows all entities as Unavailable. I followed instructions to a tee, but for some reason it's not connecting.

**Comment by fhold** [comment]
i have the same issue, currently i only have the meal plan sensor activated and i get the following error:

`Logger: custom_components.grocy
Source: custom_components/grocy/__init__.py:104
Integration: Grocy (documentation, issues)
First occurred: 10:15:02 (17 occurrences)
Last logged: 10:23:02

Update of Meal_plan failed with 'NoneType' object has no attribute 'name'`

**Comment by MagicMountainMan** [comment]
I have the same issue, but with Chores (that's all I use in Grocy though)
```
Update of Overdue_chores failed with 'NoneType' object has no attribute 'get'
Update of Chores failed with 'NoneType' object has no attribute 'get'
```

**Comment by Kubling1** [comment]
Here is the same issue. No sensors available. When i add the card i get No todos as respons. 
Heres my config:
type: custom:grocy-chores-card
entity: sensor.grocy_chores
title: Pligter
show_quantity: 7
show_days: 7
show_assigned: true
show_last_tracked: true
show_last_tracked_by: true
show_track_button: true
I have No errors to show

**Comment by isabellaalstrom** [comment]
Can you please download the latest beta version and see if your issues still persist or if you are getting some better logging.
