### ISSUE TITLE
Page does not exist when adding a product

### ISSUE THREAD

**Issue by RolandGoud** [custom-components/grocy#16]
After I add a product I get a page does not exist error

**Comment by SebRut** [comment]
Could you provide more details about what you are doing (json service data etc.) and what response you are getting?

**Comment by SebRut** [comment]
_Hey! Just wanted to let you know that I finally accepted, that I'll not be able to maintain this project for the foreseeable future. I'd be happy to hand most of this over to someone willing to work on this integration and will try to support this by working on SebRut/pygrocy._

**Comment by isabellaalstrom** [comment]
Since no more information has come in to this issue I will be closing it. Please open again or create a new issue if anyone want to supply more information.
