### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by Galapagon** [custom-components/grocy#160]
**Describe the bug**
When trying to access Grocy via Https://<URL>:9192 or https://<IP>:9192 the error in the title is created.

**Expected behavior**
Access Grocy outside of Home Assistant.

**To Reproduce**
Grocy:
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem

DuckDNS 
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  algo: secp384r1
  
  NGINX:
  certfile: fullchain.pem
  keyfile: privkey.pem
  443/tcp 443
  80/tcp disabled
  
 Add-on version: 0.15.0
 System: Home Assistant OS 6.5  (amd64 / qemux86-64)
 Home Assistant Core: 2021.10.4
 Home Assistant Supervisor: 2021.10.0

**Comment by isabellaalstrom** [comment]
This is not an issue with the integration, but rather with the add-on I'd say.
