### ISSUE TITLE
Feature request: Be able to track who did the chore based on Home-Assistant user

### ISSUE THREAD

**Issue by markmghali** [custom-components/grocy#161]
Currently when a chore is tracked it is always done by the user who created the API key. Is there a way to link home assistant user and grocy user, so the chore properly rotates between people? or I may have misconfigured my setup?

**Comment by isabellaalstrom** [comment]
There is no way of linking the home assistant user to the grocy user. However since Grocy v 3.1.0 (addon v 0.15.0) this should be possible to manually achieve. Can you try this?

**Comment by ThellraAK** [comment]
Looks like it's just adding a second value to the json thing with "done_by"

![image](https://user-images.githubusercontent.com/13631482/150557807-295260a3-d01e-4908-b3a1-f38b2019b373.png)

curl -X 'POST' \
  'http://grocy.lan:9283/api/chores/420/execute' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "tracked_time": "2022-01-21T15:53:09.523Z",
  "done_by": 69
}'


Was what I came up with in the 'examples' section of the API

**Comment by ludeeus** [comment]
@isabellaalstrom Looks like this is already implemented <https://github.com/custom-components/grocy/blob/master/custom_components/grocy/services.py#L197>
<https://github.com/custom-components/grocy/blob/master/custom_components/grocy/services.yaml#L81-L87>
