### ISSUE TITLE
Grocy integration failing due to config_flow.py

### ISSUE THREAD

**Issue by jones-alexander-phoenix** [custom-components/grocy#162]
**Describe the bug**
Integration configuration fails due to invalid URL in config_flow.py

**Expected behavior**
Add integration to home assistant

**To Reproduce**
Followed Adding the integration for Grocy add-on instructions on fresh installations of both the grocy add-on and grocy custom component. Running on a local installation of homeassistant, no ssl.

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy?**
NA

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant - 2021.10.6
Grocy - 0.15.0
Grocy custom component - 3.2.0

**How do you have Grocy installed? Add-on or external?**
Add-on

**Have you added debugging to the log, and what does the log say?**
Logger: custom_components.grocy.config_flow
Source: custom_components/grocy/config_flow.py:85
Invalid URL '/api/system/info': No schema supplied. Perhaps you meant http:///api/system/info?

**JSON service data (if related to using a service)**
NA

**Additional context**

**Comment by danielholm** [comment]
I got the same issue. Unable to add integration in HA.

**Comment by thejeffreystone** [comment]
Did you enable external port 9192 on the Grocy Add-on? I noticed it it is not enabled by default and I dont remember seeing notes anywhere that it needed to be one. 

In my fresh install the HA integration failed until it was enabled. Not sure that is it. But figured I would mention it.

**Comment by isabellaalstrom** [comment]
It doesn't seem to be getting the url from where you add the integration. How did you fill out the information?

**Comment by travi** [comment]
I'm attempting to install and running into the same failure. 

> How did you fill out the information?

The failure happens before being prompted for any information. On the Home Assistant integrations screen, I:
* clicked the "Add Integration" button
* searched for Grocy
* chose Grocy from the results list
* waited for "Please wait while Grocy is being setup"
* presented with "Error" "Config flow could not be loaded"

I don't find any entries related to Grocy in the system logs after the failure.

**Comment by ludeeus** [comment]
That is not the same, you get that one when home assistant did not install the requirements properly, try restarting Home Assistant and/or accessing home assistant with local IP when setting up custom integrations.

**Comment by ludeeus** [comment]
As for the original issue description, you get that if the URL you used does not start with `http://` or `http://`
