### ISSUE TITLE
Timestamps in sensor attributes have incorrect time zones

### ISSUE THREAD

**Issue by jonvmey** [custom-components/grocy#164]
**Describe the bug**
All of the timestamps in sensor attributes, specifically noticed in chores and tasks as that what I'm using right now, have the correct local time value but end with `+00:00` which indicates the time zone at UTC rather than my actual time zone. This becomes an issue when trying to use these attributes in a template as converting them from timestamp strings to a datetime value gives the wrong time. 

**Expected behavior**
The timestamps should either not include any timezone information so that they will (hopefully) be implicitly interpreted as local, have the correct time zone, or have the correct UTC time.

**To Reproduce**
1. Check the API value for a chore's last tracked time and it shows: `"last_tracked": "2021-12-09 10:57:53"` with local time zone being implied
2. Check the sensor attributes for that same chore and it shows `last_tracked_time: '2021-12-09T10:57:53+00:00'` which is in UTC

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy?**
All sensors are enabled and working in HA, all corresponding functions enabled in Grocy.

**What is your installed versions of Home Assistant, Grocy and this integration?**
HA 2021.11.5, Grocy 0.15.0, Integration v3.2.0

**How do you have Grocy installed? Add-on or external?**
Add-on

**Have you added debugging to the log, and what does the log say?**
No

**Additional context**
None

**Comment by isabellaalstrom** [comment]
Please fill out all of the information from the issue template.

**Comment by jonvmey** [comment]
I've added the requested additional information.

**Comment by jonvmey** [comment]
Not sure when it was fixed but I was looking at this again and the time values appear to be properly specified now as local times with no timezone which works fine for what I wanted to do with them.
