### ISSUE TITLE
Feature Request: Event when chore or task is marked as complete

### ISSUE THREAD

**Issue by NickM-27** [custom-components/grocy#165]
It would be great if when a user marks a chore or task as complete there was an event to react to that. I'm busy now but may be able to contribute this change in a few weeks.

**Comment by ludeeus** [comment]
There is already an event fired when services are executed, no need to add another event for it, just listen for the "call_service" event and filter on "grocy" as the domain and "execute_chore" as the service
<https://www.home-assistant.io/docs/configuration/events/#event-call_service>

**Comment by NickM-27** [comment]
Ah very cool, that should work well
