### ISSUE TITLE
Details on port number to be added to readme.md (Adding the integration > for existing external Grocy install > 8)

### ISSUE THREAD

**Issue by rickgardner077** [custom-components/grocy#168]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
In the readme.md installation instruction for external Grocy install (Adding the integration > for existing external Grocy install > 8) a link to https://github.com/custom-components/grocy#integration-configuration is set for further setup. The screenshot in the link shows port number 9192 to be added which does not work on external installations. This should be port 443 for https or port 80 for http access.

**Expected behavior**
This should be port 443 for https or port 80 for http access.

**To Reproduce**
Got to readme.md
Adding the integration > for existing external Grocy install > 8

### General information to help debugging:
External Grocy on dedicated server with dedicated domain address

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant OS core-2021.12.10

**How do you have Grocy installed? Add-on or external?**
External on https://grocy.domain.xyz

**Have you added debugging to the log, and what does the log say?**
not applicable

**JSON service data (if related to using a service)**
not applicable

**Additional context**

**Comment by isabellaalstrom** [comment]
The image shows an example of how you should fill out the information, but of course you have to fill it out with the information corresponding to your actual setup :) The ip is also an example, since not everyone has it on "83".
