### ISSUE TITLE
Can't set Equipment to false

### ISSUE THREAD

**Issue by RolandGoud** [custom-components/grocy#17]
On setting equipment to false the whole component fails. It looks like the equipment page is the default landing page. So whenever you set it to false in the setup it will fail (resulting in a page not found)

**Comment by Polafox** [comment]
I think @RolandGoud might actually be referring to an issue with the grocy not this integration. 
https://github.com/grocy/grocy/issues/294

**Comment by SebRut** [comment]
_Hey! Just wanted to let you know that I finally accepted, that I'll not be able to maintain this project for the foreseeable future. I'd be happy to hand most of this over to someone willing to work on this integration and will try to support this by working on SebRut/pygrocy._

**Comment by isabellaalstrom** [comment]
This is a problem with Grocy itself (addon or self installed version). Therefore I will be closing this issue.
