### ISSUE TITLE
[beta on HA OS 7.2] Component breaks due to invalid datetime format

### ISSUE THREAD

**Issue by rickgardner077** [custom-components/grocy#179]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
Updates of entities from external Grocy install not possible due to errors in datetime format. Entities show no values

**Expected behavior**
Entities from external Grocy install should be pulled and updated in Home Assistant. Entites should show values

**To Reproduce**
1. Install Grocy component from HACS
2. Restart
3. Activate integration
4. View log

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy?**
Missing_products
Overdue_chores
Shopping_list

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant OS 7.2 on Rapsberry Pi 4B 64-bit
core-2021.12.10
Grocy 3.1.3 
Integration v 4.1.4b beta

**How do you have Grocy installed? Add-on or external?**
on external server connected via https on port 443

**Have you added debugging to the log, and what does the log say?**
 Logger: custom_components.grocy
Source: custom_components/grocy/__init__.py:104
Integration: Grocy (documentation, issues)
First occurred: 14:03:54 (51 occurrences)
Last logged: 14:12:28

    Update of Missing_products failed with 1 validation error for ProductDetailsResponse last_used invalid datetime format (type=value_error.datetime)
    Update of Overdue_chores failed with 1 validation error for CurrentChoreResponse next_estimated_execution_time none is not an allowed value (type=type_error.none.not_allowed)
    Update of Shopping_list failed with 1 validation error for ProductDetailsResponse last_used invalid datetime format (type=value_error.datetime)

**JSON service data (if related to using a service)**
```json
{

}
```

**Additional context**

**Comment by renarena** [comment]
Same here. But no more barcode errors ;-)

`Update of Missing_products failed with 6 validation errors for CurrentVolatilStockResponse overdue_products -> 28 -> product -> product_group_id value is not a valid integer (type=type_error.integer) overdue_products -> 32 -> product -> product_group_id value is not a valid integer (type=type_error.integer) overdue_products -> 37 -> product -> product_group_id value is not a valid integer (type=type_error.integer) overdue_products -> 40 -> product -> product_group_id value is not a valid integer (type=type_error.integer) overdue_products -> 58 -> product -> product_group_id value is not a valid integer (type=type_error.integer) overdue_products -> 68 -> product -> product_group_id value is not a valid integer (type=type_error.integer)
Update of Overdue_tasks failed with 'tzinfo' is an invalid keyword argument for replace()
Update of Meal_plan failed with 1 validation error for MealPlanResponse product_amount value is not a valid float (type=type_error.float)
Update of Shopping_list failed with 1 validation error for ProductDetailsResponse last_used invalid datetime format (type=value_error.datetime)
Update of Stock failed with 1 validation error for CurrentStockResponse product -> min_stock_amount value is not a valid integer (type=type_error.integer)`

**Comment by Rikkie80** [comment]
Similar issue here(?) with the beta version and external Grocy install

`
2022-01-26 15:18:18 ERROR (MainThread) [custom_components.grocy] Update of Stock failed with 1 validation error for CurrentStockResponse
product -> product_group_id
value is not a valid integer (type=type_error.integer)
`

**Comment by ludeeus** [comment]
This issue is tracked in pygrocy <https://github.com/SebRut/pygrocy/issues/215>

**Comment by frankietest6** [comment]
My meal plan entity has broken with this update. It just says no meal plans found.

**Comment by ludeeus** [comment]
This issue is not an update, this is about wrong values expected in pygrocy, if your logs do not match what's already posted here, then open a separate issue.

**Comment by niklaspoulsenSH** [comment]
I have exactly same error with _Update of Meal_plan failed with 'datetime.date' object has no attribute 'date'_
Did you find an fix for this?

**Comment by rickgardner077** [comment]
Updated external Grocy install to 3.2.0, for me the error does no longer appear on component beta version 4.1.6b

**Comment by niklaspoulsenSH** [comment]
Didnt help do downgrade to 3.2.0 – still have the error: Update of Meal_plan failed with 'datetime.date' object has no attribute 'date'

Will try update to beta version
