### ISSUE TITLE
Readme configuration example doesn't work with HACS install

### ISSUE THREAD

**Issue by krihil** [custom-components/grocy#18]
**Describe the bug**
When installing the integration through HACS as described in the readme, the current configuration example doesn't work. It seems that the example configuration is using newer code that's not available from HACS (release 0.1.3).

**To Reproduce**
1. Go to your home assistant and install through HACS
2. Copy configuration example to configuration.yaml 
3. Replace URL and API-key
4. run config check. 

**Expected behavior**
Configuration example works with the version available through HACS as described. 

**Are you using HASSIO to run grocy?**
Yes

**Additional context**
When updating the files in the custom_components folder manually with the latest code downloaded directly from this repo, the config check works (as well as the integration).

**Comment by SebRut** [comment]
It seems like this github page uses the develop branch to show the README by default while HACS pulls its releases from the master branch. I pushed a new release and v0.2.0 should be available in HACS and working with the instructions in the readme.

**Comment by krihil** [comment]
Yes, Thank you. Seems to work now after the new release. In HACS it seems that you could also choose to download the develop-version, that would most likely have worked as well but it's not default either. So this change will help to get both "in sync".
