### ISSUE TITLE
sensor.grocy_stock unknown

### ISSUE THREAD

**Issue by michaeltryl** [custom-components/grocy#181]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
when i look in Developer Tools my sensor.grocy_stock is unknown
I therefore also missing all the attributes

**Expected behavior**
the sensor should show all the items I have in my grocy integration

**To Reproduce**
Thinking it has come after the last update of grocy. I have tried restarting my home assistant but it did not help

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy?**
I think I have all sensors activated. do not know where I disable them. Uses only sensor.grocy_stock, so does not know if the other sensors behave as they should, but immediately it seems to be right

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant 2021.12.10
and the newest grocy, cant find a number

**How do you have Grocy installed? Add-on or external?**
as addon

**Have you added debugging to the log, and what does the log say?**
no debug

**JSON service data (if related to using a service)**
```json
{

}
```

**Additional context**

**Comment by isabellaalstrom** [comment]
You need to enable debugging and look in the log to get relevant lines to paste here. It's impossible to even begin to guess what is wrong otherwise.  https://github.com/custom-components/grocy#troubleshooting

**Comment by michaeltryl** [comment]
Its working again. Yesterday it suddenly was back :)
