### ISSUE TITLE
Cannot substitute parent product with sub product

### ISSUE THREAD

**Issue by patrickhilker** [custom-components/grocy#182]
**Describe the bug**
When using the `grocy.consume_product_from_stock` on a "parent product" (id: 1, stock: 0) with a "sub product (id: 2, stock: 10) the service fails with a 400 error.

**Expected behavior**
The "sub product" should be consumed instead of the "parent product".

**To Reproduce**
I have `product1` (grocy id: 1, stock: 0) and `subproduct1` (grocy id: 2, stock: 10) which is a subproduct to `product1`. I make the following service call:

```
service: grocy.consume_product_from_stock
data:
  transaction_type: CONSUME
  amount: 1
  product_id: 1
```

This gives me an error 400. Calling the service with `product_id: 2` works as intended and consumes the "sub product".

This is the payload of the request the grocy ui makes, when consuming a "parent product":

```
{
    "amount":"1.0",
    "spoiled":false,
    "allow_subproduct_substitution":true
}
```

I assume that the field `allow_subproduct_substitution` should be set in the request the grocy component makes.

### General information to help debugging:

**What is your installed versions of Home Assistant, Grocy and this integration?**
Latest everywhere

**How do you have Grocy installed? Add-on or external?**
External

**Log entry from home assistant**
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: .local/lib/python3.9/site-packages/pygrocy/grocy_api_client.py:278
First occurred: 02:10:06 (4 occurrences)
Last logged: 02:43:18

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: <Response [400]>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/lib/python3.9/site-packages/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/lib/python3.9/site-packages/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/grocy/services.py", line 99, in async_call_grocy_service
    await async_consume_product_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 188, in async_consume_product_service
    await hass.async_add_executor_job(wrapper)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/services.py", line 184, in wrapper
    coordinator.api.consume_product(
  File "/config/.local/lib/python3.9/site-packages/pygrocy/grocy.py", line 144, in consume_product
    return self._api_client.consume_product(
  File "/config/.local/lib/python3.9/site-packages/pygrocy/grocy_api_client.py", line 391, in consume_product
    self._do_post_request(f"stock/products/{product_id}/consume", data)
  File "/config/.local/lib/python3.9/site-packages/pygrocy/grocy_api_client.py", line 278, in _do_post_request
    raise GrocyError(resp)
pygrocy.errors.grocy_error.GrocyError: <Response [400]>
```

**Comment by kingo55** [comment]
I've just replicated this too. It seems like a bug upstream and not with this repository. Here's consumption on a parent product directly via the API:

<img width="1213" alt="Screen Shot 2022-02-24 at 10 12 08 pm" src="https://user-images.githubusercontent.com/2361388/155514163-624df15b-28e0-448a-9002-baa55668ba5e.png">

And here's consumption on a sub product:

<img width="1204" alt="Screen Shot 2022-02-24 at 10 13 29 pm" src="https://user-images.githubusercontent.com/2361388/155514323-c8457ab0-00ef-477b-8c95-4fa47ea69b5b.png">

Will log this upstream in case it hasn't been logged already.

**Comment by kingo55** [comment]
Upon further research, it looks like we're missing the parameter "allow_product_substitution". There's currently no way to add that into this extension.

Source: https://github.com/grocy/grocy/issues/1767

**Comment by kingo55** [comment]
Until we have pygrocy support for "allow_subproduct_substitution" we won't be able to support parent products consumption. If I get time, I might submit a PR upstream.

**Comment by rickthegeek** [comment]
I ran into this issue as well, it looks like pygrocy got the "allow_product_substitution" support merged in. I look forward to seeing if it fixes the issue once support is added to the component. I am trying to make things as automatic as possible for other non-geek household members....

**Comment by kingo55** [comment]
Yes, it might be some time before we can include this here because although it's merged upstream, he needs to make a release of it.

You may need to call the API directly if you need a quick fix for this for the interim.
