### ISSUE TITLE
"binary_sensor.grocy_overdue_chores" does not update if [Track Date Only] is checked in chore master data

### ISSUE THREAD

**Issue by rickgardner077** [custom-components/grocy#188]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
If a chore has track_date_only=1 overdue chores are not registered in Home Assistant

**Expected behavior**
Overdue chore should be registered no matter if box is checked or not

**To Reproduce**
1. [Edit Chore] in Grocy
2. Check [Track Date Only]
3. Look at binary_sensor.grocy_overdue_chores

### General information to help debugging:

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant 2022.2.8
Home Assistant OS 7.4
Grocy component v4.1.6b

**How do you have Grocy installed? Add-on or external?**
External

**Have you added debugging to the log, and what does the log say?**
`2022-02-18 10:37:13 DEBUG (SyncWorker_8) [pygrocy.grocy_api_client] b'{"chore":{"id":"1","name":"chore_name","description":"","period_type":"daily","period_days":"1","row_created_timestamp":"2022-01-25 10:35:47","period_config":"","track_date_only":"1","rollover":"1","assignment_type":"in-alphabetical-order","assignment_config":"1","next_execution_assigned_to_user_id":"1","consume_product_on_execution":"0","product_id":"","product_amount":null,"period_interval":"30","active":"1","start_date":"2021-12-13 00:00:00"},"last_tracked":"2021-12-13 `

**JSON service data (if related to using a service)**
```json
{

}
```

**Additional context**

**Comment by isabellaalstrom** [comment]
I use this feature on almost all of my chores and my sensors are working just fine. I would need some more information. Does everything else work? The regular "sensor.grocy_chores" for example.
