### ISSUE TITLE
Unable to complete config flow, if addon ssl: true

### ISSUE THREAD

**Issue by sym0nd0** [custom-components/grocy#204]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
When trying to complete integration setup hitting an error of "something went wrong" on submit - doesn't matter if URL is `http` or `https` or verify ssl is enabled or not.

After some digging, it appears that the integration installation will only complete if the addon configuration is set to `ssl: false`.

**Expected behavior**
Submitting completes integration install

**To Reproduce**
1. Follow the [Adding the integration for Grocy add-on](https://github.com/custom-components/grocy) instructions to point 10
2. Click submit
3. `Something went wrong`
4. Amend Grocy addon configuration, changing `ssl: true` to `ssl: false`
5. Restart addon
6. Goto 1
7. Profit 

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy?**
```
binary_sensor.grocy_expired_products
binary_sensor.grocy_expiring_products
binary_sensor.grocy_missing_products
binary_sensor.grocy_overdue_chores
binary_sensor.grocy_overdue_tasks
sensor.grocy_chores
sensor.grocy_meal_plan
sensor.grocy_shopping_list
sensor.grocy_stock
sensor.grocy_tasks
```

All entities showing as disabled. Only chores enabled in Grocy config.

**What is your installed versions of Home Assistant, Grocy and this integration?**
HA `core-2022.4.1`
Grocy `3.2.0` 
HA integration `4.1.8`

**How do you have Grocy installed? Add-on or external?**
Addon `0.17.0`

**Have you added debugging to the log, and what does the log say?**
N/A

**JSON service data (if related to using a service)**
N/A

**Additional context**
N/A

**Comment by sym0nd0** [comment]
Decided to start fresh with Grocy, so uninstalled everything and reinstalled using `4.2.0b` for the integration, to see if this problem is resolved in an upcoming release. Same issue.

Default addon config, with required port.
![image](https://user-images.githubusercontent.com/55590428/163673486-2b0d92b8-27d4-4247-9cb9-144d78f1f579.png)
Trying with SSL.
![image](https://user-images.githubusercontent.com/55590428/163673592-8e4f77d1-b2fa-454d-91c3-9235f5080f7e.png)
Nope.
![image](https://user-images.githubusercontent.com/55590428/163673621-b0b216cd-3903-4706-b461-eaf9d0fbabf4.png)
Trying without SSL.
![image](https://user-images.githubusercontent.com/55590428/163673679-c6b8a6fb-eaa1-4c98-b0e1-186e1930d440.png)
Nope.
![image](https://user-images.githubusercontent.com/55590428/163673693-1755c849-7b3d-49f1-99a9-dde139e8c1c8.png)

Config amended, setting SSL to false and addon restarted.
![image](https://user-images.githubusercontent.com/55590428/163673746-2ff2b16c-2127-4401-af63-2dc7d28f605e.png)
Great success.
![image](https://user-images.githubusercontent.com/55590428/163673883-66946608-e8ed-41c2-ab1d-2158d997d2a3.png)

¯\\__(ツ)__/¯

**Comment by ludeeus** [comment]
If addon have `ssl: true`, you need to use `https` not `http`
If you are also using IP instead of the hostname the certificate is issued to, you can not enable SSL verification.

**Comment by sym0nd0** [comment]
![image](https://user-images.githubusercontent.com/55590428/163674514-b03aafd1-e98f-4bf2-a89d-04b41b2eae48.png)

![image](https://user-images.githubusercontent.com/55590428/163674526-c5cd9eea-8790-4fb8-ab25-ccf2af2ee06b.png)

![image](https://user-images.githubusercontent.com/55590428/163674582-b5af0a59-c974-4a42-bf45-b6b16fc00723.png)

![image](https://user-images.githubusercontent.com/55590428/163674592-19a4ae10-534a-441d-90c3-f0e7bea55167.png)

???

**Comment by ludeeus** [comment]
```
URL: https://xxxx.duckdns.org
PORT: 9192
```
This requires you to have opened that port in your firewall `https://xxxx.duckdns.org:9192` you use to test
