### ISSUE TITLE
Invalid version number prevents integration v4.3.3b from starting

### ISSUE THREAD

**Issue by marcelvriend** [custom-components/grocy#223]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
With #221 the integration won't start, unless the version number is valid for HA. Sorry, I should have mentioned that in the PR.
The 'b' postfix makes it invalid for HA. 

_The custom integration 'grocy' does not have a valid version key (v4.3.3b) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details_

**Expected behavior**
Versioning without 'b' will fix it.
@isabellaalstrom Can you do a release without 'b' from now on? Of course, you can still make it a pre-release.

**To Reproduce**

Install latest beta v4.3.3b.

**Comment by ludeeus** [comment]
` v4.3.3b[1-9]` _should_ also be valid

**Comment by isabellaalstrom** [comment]
Fixed, re-released as v4.3.3
