### ISSUE TITLE
Data sensor can not be templated in HA

### ISSUE THREAD

**Issue by BlueBlueBlob** [custom-components/grocy#23]
HA version : 0.100.3
Jsonpickle returns a string and not a list of dictionaries.
So when you try to template, you can not because items attribute is just a big string.
I can fix it.

**Comment by BlueBlueBlob** [comment]
Maybe it's related to this https://www.home-assistant.io/blog/#goodbye-json-

**Comment by SebRut** [comment]
Were you able to evaluate this?

**Comment by BlueBlueBlob** [comment]
Sorry. I will do a pull request

**Comment by SebRut** [comment]
Don't worry, just trying to clean up some issues ^^
