### ISSUE TITLE
Can you update pygrocy requirement to 1.5.0 ? There is an issue with pydantic version requirement which was solved in pygrocy 1.5.0

### ISSUE THREAD

**Issue by grzech1983** [custom-components/grocy#251]
Hello,

currently when I try to install Grocy component I'm getting error:

```
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 12:22:02 (3 occurrences)
Last logged: 12:22:14

Unable to install package pygrocy==1.4.1: ERROR: Will not install to the user site because it will lack sys.path precedence to pydantic in /snap/home-assistant-snap/527/lib/python3.10/site-packages
```

this is related to pygrocy 1.4.1 require older version od pydantic which is already installed. This has been resolved here:

https://github.com/SebRut/pygrocy/commit/6d5dae76efbcf0abe06baafaaf4461bcb66db541#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

in pygrocy 1.5.0 release.

Thanks

**Comment by grzech1983** [comment]
It looks like upgrade pygrocy to 1.5 is also fixing other issue:

https://github.com/custom-components/grocy/issues/241#issuecomment-1252092857

**Comment by excalbian** [comment]
I'm not 💯 but it seems that the upgrade to `pygrocy` 1.5.0 will cause issues with timezone support for the `execute_chore` service (see #252 for details). Still 🕵️ as my python is a bit rusty (barely used).
