### ISSUE TITLE
Home assistant warns about future failure in component

### ISSUE THREAD

**Issue by FHeilmann** [custom-components/grocy#264]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
Home-assistant 2023.3 informs about a deprecation of sorts in the grocy integration:

```
Log Details (WARNING)
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 12:39:46 PM (1 occurrences)
Last logged: 12:39:46 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for grocy using this method at custom_components/grocy/__init__.py, line 52: hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
```

**Expected behavior**
Grocy integration starts up with no errors in the logs

**To Reproduce**
- Install latest grocy component beta in home assistant > 2023.3
- Open logs

**Comment by cdouet** [comment]
Yes, same on my home assistant yellow with 2023.4.1

**Comment by cdouet** [comment]
This is fixed by:
https://github.com/custom-components/grocy/pull/260
