### ISSUE TITLE
Due in days is .nan

### ISSUE THREAD

**Issue by isabellaalstrom** [custom-components/grocy#38]
**Describe the bug**
Due in days for a chore is `.nan`.
Extract from sensor:
```attribution: Data from this is provided by grocy.
items:
  - _chore_id: 1
    _last_tracked_time: '2019-12-13T00:00:00+00:00'
    _next_estimated_execution_time: '2019-12-27T00:00:00+00:00'
    _name: Wash cloths
    _last_done_by:
      _id: 2
      _username: Isa
      _first_name: ''
      _last_name: ''
      _display_name: Isa
    dueInDays: .nan
```

**To Reproduce**
I re-added the sensor through config flow and this is what the sensor now shows.

**Expected behavior**
Due in days should be a date :)

**Are you using HASSIO to run grocy?**
Yes

**Comment by isabellaalstrom** [comment]
My bad, that was some kind of weird leftover I guess? Working now with _next_estimated_execution_time

**Comment by BlueBlueBlob** [comment]
Depends on your Grocy version (the API version).
You can have weird results (like missing products), because of bug in Grocy or an old version.
But for now I think add-on and Grocy are on same version.

Btw I don't have this field ! What's your Grocy version ?

**Comment by isabellaalstrom** [comment]
I think it must have been a left over or something, because it disappeared of it self.. Not an issue anymore!
