### ISSUE TITLE
Grocy services do not immediately update related sensor(s)

### ISSUE THREAD

**Issue by cerebrate** [custom-components/grocy#40]
**Describe the bug**

Grocy data displayed in the HA UI (for example, a list of chores displayed using _lovelace-grocy-custom-card_) does not update immediately when a service call is made (i.e., the _grocy.execute_chore_ service provided by this installation, which is used by the aforementioned card to track chore execution on a button press). This is confusing to the user, as the button or other UI element invoking the service appears to have no immediate effect.

**To Reproduce**
1. Add a chore to Grocy, on a HA system in which this custom component and _lovelace-grocy-custom-card_ are installed.
2. Add a card to the UI with the following configuration:

```
entity: sensor.grocy_chores
type: 'custom:grocy-chores-card'
```
3. Exit UI configuration.
4. Click the "track" button to the right of the displayed chore.
5. Observe that the "Last tracked:" date does not update immediately (but rather at the end of the next 60-second update interval).

**Expected behavior**

The last tracked date should update immediately after the button is pressed; i.e., the change in the Grocy chore data should be reported immediately by the grocy_chores sensor.

**Are you using HASSIO to run grocy?**
Yes

**Additional context**

I have not yet checked if this same behavior occurs with regard to stock/shopping list displays and those services, but the code suggests that it will, and this should probably also be fixed.

**Comment by BlueBlueBlob** [comment]
Hi

Check Grocy add-on cpu usage when you change something in Grocy. Since we don't know what data changed we can only update all sensors at the same time.  And it's a lot of requests (depending on your Grocy data) and time :/

Waiting for this https://github.com/grocy/grocy/issues/461

BTW it's same issue for all sensors.
On my rpi3 it takes 2 minutes to update the shopping list :/

**Comment by cerebrate** [comment]
Hm. Since this is mostly problematic when the Grocy data is changed by one of the custom component’s services, shouldn’t we know what’s changed because we just made the API call that changed it?

So we could force an update of grocy.chores at the end of a grocy.execute_chore call, for example. 

(I’ve experimented with this a little, but I’m not familiar enough yet with the HA API and asynchronous python to have made much progress.)

**Comment by BlueBlueBlob** [comment]
You are right. Thanks for the idea.
Keep in touch :)
