### ISSUE TITLE
Entity or any sensor for Grocy tasks not showing

### ISSUE THREAD

**Issue by yeowan** [custom-components/grocy#43]
First of all - excellent project, I am just starting with Grocy and HA integration and it  already changed my life a bit. Thanks!

Are the Grocy tasks supported?
I can only see the stock, the shopping list and the chores in entities and only 3 related services. (Add / consume product, track chore)
I can live without recipes and other stuff, but the tasks support would be essential to be integrated to HA.
Like send a mail notification when a task is nearly overdue.

**Comment by SebRut** [comment]
_Hey! Just wanted to let you know that I finally accepted, that I'll not be able to maintain this project for the foreseeable future. I'd be happy to hand most of this over to someone willing to work on this integration and will try to support this by working on SebRut/pygrocy._
