### ISSUE TITLE
Malformed URL Request

### ISSUE THREAD

**Issue by firstof9** [custom-components/grocy#47]
**Describe the bug**
The integration is not using the URL input into the configuration correctly.

**To Reproduce**
1. Configure integration with sub folder.
2. See error

**Expected behavior**

**Are you using HASSIO to run grocy?**
No

**configuration.yaml entry**
Configured from the UI
```
URL: https://<my_valid_TLD>/grocy/
Port: 443
API: <redacted>
```

**JSON service data (if related to using a service)**
n/a

**Additional context**
access.log inside grocy container:
```
[06/May/2020:11:10:19 -0700] "GET /:443/api/system/db-changed-time HTTP/1.1" 404 328 "-" "python-requests/2.23.0"
```

Yes my instance of grocy works at ```https://<my_valid_tld>/grocy/```

**Comment by SebRut** [comment]
Hi! Could you try to remove the trailing `/` in the configured URL please?

**Comment by firstof9** [comment]
I tried it without and it still failed to work the / seemed to get added on. I've since changed my install to use a subdomain.

**Comment by tikismoke** [comment]
I have the same problem. I'm sure it's in the grocy python api error.
Got this and indeed it's not a working url at all since port is not put at the right place...
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://grocy.localdomain/grocy/public/:80/api/stock
`

**Comment by SebRut** [comment]
Try to remove the trailing slash in the URL

**Comment by isabellaalstrom** [comment]
Do you guys have the stock enabled in Grocy?

**Comment by tikismoke** [comment]
> Try to remove the trailing slash in the URL

Same the issue is in url encoding in python grocy. I'm going to open issue in the lib.
As you see the requests could be right if the port ':80' was not place where it is. (:80 should be behind the adress or ip of the host not behind the whole url)

**Comment by isabellaalstrom** [comment]
@tikismoke Whats the url in the config?

**Comment by tikismoke** [comment]
> @tikismoke Whats the url in the config?

http://grocy.localdomain/grocy/public/

**Comment by isabellaalstrom** [comment]
Yeah, the component and lib is made to work with http(s)://adress:port. If there's paths after it doesn't work. So it's not really a bug, but your config is not supported as of now. You can of course still make an issue for it.

**Comment by tikismoke** [comment]
Also i not that if chores is not available (disable in config php of grocy, the components do not recover anything else :(

**Comment by tikismoke** [comment]
https://github.com/SebRut/pygrocy/issues/121

**Comment by isabellaalstrom** [comment]
Yes, I'm working on being able to pick which sensors you'd like to have, then you can disable the ones you don't have in Grocy or just don't want to have in Home Assistant.

**Comment by tikismoke** [comment]
> Yes, I'm working on being able to pick which sensors you'd like to have, then you can disable the ones you don't have in Grocy or just don't want to have in Home Assistant.

https://github.com/custom-components/grocy/issues/77 :+1:
