### ISSUE TITLE
Feature Request: Show assigned names for chores, or allow multiple cards for different users.

### ISSUE THREAD

**Issue by batfasturd** [custom-components/grocy#48]
The chore card does not show who the chore is attached too which makes it harder to determine who's day / job it is to do it. It would be nice to either show the user it's assigned to or select a user per card so I can have a different card for each person doing chores.

**Comment by adtwomey** [comment]
yep I about to ask this

**Comment by SebRut** [comment]
Hi! This repo is only responsible for providing an grocy integration for HA! Please check the grocy chore card repo for issues related to cards: https://github.com/isabellaalstrom/lovelace-grocy-chores-card

**Comment by adtwomey** [comment]
Can you reopen....

![Screenshot_20200601-205354_Samsung Internet](https://user-images.githubusercontent.com/14849762/83402686-88ed2700-a44a-11ea-8581-772b13970d3f.jpg)
