### ISSUE TITLE
Add documentation how to use API with ingress

### ISSUE THREAD

**Issue by oncleben31** [custom-components/grocy#7]
Since the latest update of the add-on it is possible to use Ingress and Igress is activated by default.
With Ingress, the API URL visible in the Grocy UI seems to not be usable with your custom integration.

According to https://github.com/hassio-addons/addon-grocy/issues/31, the workaround is to use Ingress and expose the add-on thru a port.

**Comment by SebRut** [comment]
I don't have a Hass.io setup available so it would be nice if someone using hass.io could try to figure out getting the component to work and provide instructions. If you're able to access grocy's API from your browser or your HA host via curl or something like that the component should work with it.

**Comment by ludeeus** [comment]
Ingress provides both a proxy and authentication, IMO adding instructions for how to disable that (setting a port) is out of the scope of this integration.

**Comment by oncleben31** [comment]
OK But at least you could promote the workaround.

**Comment by frenck** [comment]
It is not a workaround, this is how it work in general. Adding that "workaround" to every single part of all things out there, sounds IMHO a bit overdone.

**Comment by oncleben31** [comment]
I understand that. You have more experiences and a better understanding of the big picture.
My experience is this knowledge is not obvious and it took me 2 hours of test and try before finding the solution in a close issue on github. I just want to avoid other new comers to have the same difficulties.

**Comment by rscafidi** [comment]
I'm a new comer having the same difficulties.  So what do I need to read up on to configure HA/grocy properly to use the API?  Same exact issue as was posted in https://github.com/hassio-addons/addon-grocy/issues/31 and I know several other people on the HA discord having the same issue.
