### ISSUE TITLE
Exception in log if setup fails without an existing logger

### ISSUE THREAD

**Issue by SebRut** [custom-components/grocy#73]
**Describe the bug**
The setup fails when no logger is defined and an error occurs.
Log output:

```
...
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/grocy/config_flow.py", line 33, in async_step_user
    valid = await self._test_credentials(
  File "/config/custom_components/grocy/config_flow.py", line 92, in _test_credentials
    _LOGGER.exception(e)
NameError: name '_LOGGER' is not defined
```

**To Reproduce**
Try to configure the Grocy component with the default dev container.

**Expected behavior**
Being able to successfully configure the component with the UI.

**Are you using HASSIO to run grocy?**
No

**configuration.yaml entry**
_Not applicable, as failing in configuration_

**Additional context**
* I'm trying to use the component in the default dev container.

**Comment by isabellaalstrom** [comment]
fixed in #74
