### ISSUE TITLE
Improvement: Add Sensor to track if any chores/tasks are overdue

### ISSUE THREAD

**Issue by csharpWorm** [custom-components/grocy#78]
It would be nice to have a sensor that states whether any chores or tasks are overdue.  Making it easier to write automations based on this information.  I currently would like to use this information to disable certain electronics in the event an item is overdue and haven't found a way to accomplish determining if an item is overdue just yet with my limited knowledge of HA.

**Comment by isabellaalstrom** [comment]
That is a great idea! I will add it to the board for future implementation.

**Comment by isabellaalstrom** [comment]
Done with https://github.com/custom-components/grocy/pull/95 and in v2.0.0-beta4, out now.
