### ISSUE TITLE
Revamp README.md

### ISSUE THREAD

**Issue by SebRut** [custom-components/grocy#79]
Idea list

- HASSIO instructions contain duplicate instructions (see #72)

**Comment by ludeeus** [comment]
Network section has moved in the "hassio" (supervisor) panel, image should be updated.
All refrences to "hass.io" should be removed and replaced with "supervisor" and/or (supervised / Home Assistant OS) if needed.

**Comment by isabellaalstrom** [comment]
Point out that you have to enable for example "chores" in Grocy for the chores sensors to work.

**Comment by isabellaalstrom** [comment]
Only enable entities that matches enabled features in Grocy

**Comment by ludeeus** [comment]
> Only enable entities that matches enabled features in Grocy

No need, you will guard against that with #87 ;)

**Comment by isabellaalstrom** [comment]
Added some new info and a new screenshot, but I would still like to add more information to the readme.
