### ISSUE TITLE
HA front end stuck when loading grocy custom-component

### ISSUE THREAD

**Issue by MrBLJ** [custom-components/grocy#85]
**Describe the bug**
HA front end is not accessible when adding the component through HA UI -> integrations.

**To Reproduce**
1. Install grocy custom-component.
2. Add grocy's integration.
3. HA front-end is stuck in a loading loop (logo & spinner). HA seems to be ok otherwise (all automations working).
![image](https://user-images.githubusercontent.com/12542442/91969511-7cf95580-ed16-11ea-8e4f-17b9c4f697b7.png)

**Expected behavior**
Front-end should load.

**Are you using HASSIO to run grocy?**
No.
Home assistant & grocy in docker (image: linuxserver/grocy).

**configuration.yaml entry**
None - Everything's handled through integrations UI, which I can't access when using the component.

**Additional context**
UI is still responsive 30s after reboot ... guess it's the time required to load the component. I can still remove the integration so there's no big trouble, but it's a shame because this component looks very useful.

**Comment by isabellaalstrom** [comment]
This will hopefully be solved in refactoring!

**Comment by isabellaalstrom** [comment]
Beta för 2.0 is out. I would be very happy if you could download it and check if the issue persists. To download a beta via Hacs, if you haven't before, press the tre dots at the integration and choose reinstall, then you can choose to show beta releases.

**Comment by MrBLJ** [comment]
Updated to v2.0 b3, so far the issue seems to be resolved. Thanks for your help and the work you put into this !
