### ISSUE TITLE
It's not clear what the GROCY URL is supposed to be.

### ISSUE THREAD

**Issue by arretx** [custom-components/grocy#9]
So far I've crashed HASS.io twice now trying to run this custom component.

There are two different URLs that I see when it comes to Grocy.

* There's the https://mydomain.domain.com:8123/dockercontainer_grocy
* ...and https://mydomain.domain.com:8123/api/hassio_ingress/N6GKZPOgN3kRYnh_I7BoR4i9pGhgKGuUcKYzkWbLiNU/api

Neither of them work when inserted as the config in config.

**Comment by Shadowbreed** [comment]
Having the same issue, several crashes later I've had to remove it for now

**Comment by SebRut** [comment]
It seems like hass.io users need to use port redirect stuff to access the api, hassio-addons/addon-grocy#31.
