### ISSUE TITLE
BinarySensorDevice is deprecated

### ISSUE THREAD

**Issue by fredamn76** [custom-components/grocy#99]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
I get the following error message in my logs "BinarySensorDevice is deprecated, modify GrocyBinarySensor to extend BinarySensorEntity"

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant Home, 0.115.0b12
Grocy Home Assistant addon: 0.9.1
Grocy, 2.7.1

**How do you have Grocy installed? Add-on or external?**
Addon
**Have you added debugging to the log, and what does the log say?**

**Comment by sweetgman** [comment]
Replace BinarySensorDevice with BinarySensorEntity in two places, line 3 and 36 in the binary_sensor.py
